"""initial migration

Revision ID: 408ed72e987b
Revises: 
Create Date: 2023-12-31 15:05:12.207783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "408ed72e987b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("counter", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint("uq_name", ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("counter", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
